backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/blog"
public_folder: "/assets/blog"

collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }  # Changed datetime to date
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageALT", widget: "string" }
      - { label: "SEO Title", name: "seo_title", widget: "string", required: false }
      - { label: "SEO Description", name: "seo_description", widget: "text", required: false }
      - { label: "SEO Keywords", name: "seo_keywords", widget: "list", required: false }
      - { label: "SEO Image", name: "seo_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
